from __future__ import annotations


MAX_RECOMMENDATION_MESSAGE_WORDS = 56
_PRIORITY_WEIGHT = {"high": 3, "normal": 2, "low": 1}

FIRST_STEP_RECOMMENDATION_TYPE = "first_step"
AFTER_COMPLETION_RECOMMENDATION_TYPE = "after_completion"
ON_TRACK_SUPPORT_RECOMMENDATION_TYPE = "on_track_support"
STREAK_MAINTENANCE_RECOMMENDATION_TYPE = "streak_maintenance"
STREAK_SUPPORT_RECOMMENDATION_TYPE = "streak_support"
RISK_IGNORED_RECOVERY_RECOMMENDATION_TYPE = "risk_ignored_recovery"
RESET_PLAN_RECOMMENDATION_TYPE = "reset_plan"
MISS_STREAK_RECOVERY_RECOMMENDATION_TYPE = "miss_streak_recovery"
EARLY_RECOVERY_RECOMMENDATION_TYPE = "early_recovery"
RISK_RECOVERY_RECOMMENDATION_TYPE = "risk_recovery"
SOFT_RECOVERY_RECOMMENDATION_TYPE = "soft_recovery"
PLAN_AHEAD_RECOMMENDATION_TYPE = "plan_ahead"
DATA_COLLECTION_RECOMMENDATION_TYPE = "data_collection"
KEEP_REGULAR_RECOMMENDATION_TYPE = "keep_regular"

_AI_SCENARIO_TYPES = {
    FIRST_STEP_RECOMMENDATION_TYPE,
    AFTER_COMPLETION_RECOMMENDATION_TYPE,
    ON_TRACK_SUPPORT_RECOMMENDATION_TYPE,
    STREAK_MAINTENANCE_RECOMMENDATION_TYPE,
    STREAK_SUPPORT_RECOMMENDATION_TYPE,
    RISK_IGNORED_RECOVERY_RECOMMENDATION_TYPE,
    RESET_PLAN_RECOMMENDATION_TYPE,
    MISS_STREAK_RECOVERY_RECOMMENDATION_TYPE,
    EARLY_RECOVERY_RECOMMENDATION_TYPE,
    RISK_RECOVERY_RECOMMENDATION_TYPE,
    SOFT_RECOVERY_RECOMMENDATION_TYPE,
    PLAN_AHEAD_RECOMMENDATION_TYPE,
}

_RECOVERY_SCENARIO_TYPES = {
    RISK_IGNORED_RECOVERY_RECOMMENDATION_TYPE,
    RESET_PLAN_RECOMMENDATION_TYPE,
    MISS_STREAK_RECOVERY_RECOMMENDATION_TYPE,
    EARLY_RECOVERY_RECOMMENDATION_TYPE,
    RISK_RECOVERY_RECOMMENDATION_TYPE,
    SOFT_RECOVERY_RECOMMENDATION_TYPE,
    # Legacy recommendation types can still be present in existing rows.
    "recovery_mode",
    "reduce_difficulty",
    "soft_reminder",
    "restore_regular_activity",
}
